# syntax=docker/dockerfile:1

# Base image with Ruby
ARG RUBY_VERSION=3.4.5
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Set working directory
WORKDIR /rails

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

# Install necessary packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
        curl \
        default-mysql-client \
        build-essential \
        libjemalloc2 \
        libvips \
        default-libmysqlclient-dev \
        git \
        nodejs \
        npm \
        libyaml-dev \
        imagemagick \
        pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# sudo apt-get install libyaml-dev
# gem install rails -v 8.0.2.1
# rails new saludtech --api

# RUN npm install -g yarn

# Environment variables for development
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT=""

# Install application dependencies
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Install specific version of system rake
# RUN gem install rake -v 13.2.1

# Add rails bin directory to path variable
ENV PATH="/rails/bin:${PATH}"

# Add the application source code
COPY . .

# Add a non-root user for development
USER root

# Ports for Rails (3000) and debugging tools
EXPOSE 3000

# Entrypoint and default command
CMD ["bin/rails", "server", "-b", "0.0.0.0"]